### ISSUE TITLE
double ###

### ISSUE THREAD

**Issue by nitool** [nitool/http-requests-tester#5]
```
###

### Grant password
GET url...
```

results in error 
```
TypeError: Cannot read property 'match' of undefined
    at applyClientVariable (/usr/local/lib/node_modules/http-requests-tester/src/tester.js:21:26)
    at TestCase.makeRequest (/usr/local/lib/node_modules/http-requests-tester/src/tester.js:136:27)
    at new Promise (<anonymous>)
    at TestCase.createRequestPromise (/usr/local/lib/node_modules/http-requests-tester/src/tester.js:201:16)
    at /usr/local/lib/node_modules/http-requests-tester/src/tester.js:258:34
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by nitool** [comment]
pushed to develop
